# Torch Geometric MPNN Configuration

n_enc_dim: 5
e_enc_dim: 3
model_dim: 64
num_layers: 3
node_aggr: mean  # https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#aggregation-operators
act: ReLU
residual: True
loss: L1Loss

optimizer:
  lr: 1e-4
  wd: 1e-2