# Torch Geometric MPNN Configuration

n_enc_dim: 2
e_enc_dim: 1
model_dim: 32
num_layers: 3
node_aggr: mean  # https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#aggregation-operators
act: ReLU
residual: True

optimizer:
  lr: 1e-4
  wd: 1e-2