cand_size: 10
device: cuda:2
dir: datas/models/
num_eval: 2000
seed: 42
save_dir: PBS/eval/
solver_dir: PBS/pbs/

model:
  aggr: max
  delta: 1
  dim: 64
  num_layers: 3
  readout: sum
  type: MPNN

optimizer:
  lr: 1e-4
  weight_decay: 1e-2