batch_size: 100
device: cuda:0
epochs: 100
num_train: 8000
num_val: 2000
seed: 42
val: True
wandb: True

model:
  aggr: max
  delta: 5
  dim: 64
  num_layers: 3
  readout: sum
  type: MPNN

optimizer:
  lr: 1e-4
  weight_decay: 1e-2