batch_size: 100
device: cuda:3
epochs: 100
num_train: 8000
num_val: 2000
seed: 42
wandb: True

model:
  aggr: max
  delta: 1
  dim: 64
  num_layers: 3
  readout: sum
  type: MPNN

optimizer:
  lr: 1e-4
  weight_decay: 1e-2